import "./globals.css";
import Navbar from "@/components/Resume/Navbar";

export const metadata = {
  title: "Hamza Ahmed Sheikh Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

